#!/usr/bin/env python3
"""
meta_cycle.py
-------------
Performs a reflective cycle:
  A → D(dry) → B
Respects safety modes, emits telemetry pulses for coherence tracking.
"""

import json, os
from datetime import datetime

class Skill:
    name = "meta_cycle"
    description = "Run A→D(dry)→B meta-cycle; respects safety mode and logs telemetry."

    def run(self, params):
        from skills.manager import SkillManager
        mgr = SkillManager()
        for m in ("load", "load_all", "discover", "init"):
            if hasattr(mgr, m):
                try:
                    getattr(mgr, m)()
                except Exception:
                    pass

        out = {}
        try:
            from mode import get_mode
            mode, auto = get_mode()
            out["mode"] = {"mode": mode, "autonomy": auto}
            if mode not in ("safe", "research"):
                return {"ok": False, "error": f"meta_cycle blocked in mode={mode}"}
        except Exception as e:
            out["mode_error"] = str(e)

        # Step A: introspection
        a = mgr.run("introspect", {})
        out["introspect"] = a

        # Step D: dry-run skill generation
        proposed = (params or {}).get("proposed_skill", "echo_test")
        d = mgr.run("codeforge", {
            "name": proposed,
            "description": "Generated by meta_cycle (dry run).",
            "dry": True
        })
        out["codeforge"] = d

        # Step B: journal summary
        summary = {
            "introspect_ok": bool(a.get("ok")),
            "codeforge_ok": bool(d.get("ok")),
            "proposed": proposed
        }
        b = mgr.run("journal", {"kind": "meta_cycle", "data": summary})
        out["journal"] = b

        # --- Telemetry pulse ---
        try:
            data = {
                "timestamp": datetime.utcnow().isoformat(),
                "C": 1.0,
                "Sf": 0.0,
                "kappa": 0.0,
                "Fi": 1.0,
                "module": self.name
            }
            os.makedirs("logs", exist_ok=True)
            with open("logs/telemetry.log", "a") as f:
                f.write(json.dumps(data) + "\n")
            out["telemetry"] = data
        except Exception as e:
            out["telemetry_error"] = str(e)

        return {"ok": True, "output": json.dumps(out, indent=2)}

def run(params):
    return Skill().run(params)

